### ISSUE TITLE
TypeError: this.handlerObject._init is not a function 

### ISSUE THREAD

**Issue by cirruspl** [Zimbra-Community/spoofing-and-phishing-alert-zimlet#5]
Error:
TypeError: this.handlerObject._init is not a function 

in Zimbra 8.8.9_GA_2055

In guess it's connected to:
https://github.com/Zimbra-Community/pgp-zimlet/issues/216

**Comment by barrydegraaff** [comment]
This is almost always a result of cache corruption. 

Try and undeploy and deploy some zimlets make sure to zmprov fc all, zmmailboxdctl restart and reset your browser. Then it should work
