### ISSUE TITLE
How to improve this zimet

### ISSUE THREAD

**Issue by zimico** [Zimbra-Community/spoofing-and-phishing-alert-zimlet#9]
Dear,
We received some mails which is spams. The spam score of some mails is high but not enough to make those mails spam. Other mail has low spam score. For example, this one is high spam score but there is no alert when user opens mail. 
Return-Path: <Nana.Nkrumah@kinross.com>
Received: from zmail01.zimbravn.com (LHLO zmail01.zimbravn.com)
 (103.95.197.25) by zmail01.zimbravn.com with LMTP; Fri, 21 Feb 2020
 00:30:41 +0700 (ICT)
Received: from localhost (localhost [127.0.0.1])
	by zmail01.zimbravn.com (Postfix) with ESMTP id D1CA694027
	for <cuongnt@aisc.com.vn>; Fri, 21 Feb 2020 00:30:40 +0700 (+07)
X-Virus-Scanned: amavisd-new at zimbravn.com
X-Spam-Flag: NO
X-Spam-Score: 3.488
X-Spam-Level: ***
X-Spam-Status: No, score=3.488 required=4 tests=[HTML_MESSAGE=0.001,
	RCVD_IN_BL_SPAMCOP_NET=1.347, RCVD_IN_RP_RNBL=1.51, RDNS_NONE=0.1,
	SUBJ_ALL_CAPS=0.5, T_ISO_ATTACH=0.01, T_SPF_HELO_PERMERROR=0.01,
	T_SPF_PERMERROR=0.01] autolearn=no autolearn_force=no
Received: from zmail01.zimbravn.com ([127.0.0.1])
	by localhost (zmail01.zimbravn.com [127.0.0.1]) (amavisd-new, port 10024)
	with ESMTP id TfTusP07X3Xb for <cuongnt@aisc.com.vn>;
	Fri, 21 Feb 2020 00:30:38 +0700 (+07)
Received: from kinross.com (unknown [5.181.166.43])
	by zmail01.zimbravn.com (Postfix) with ESMTP id 8FC1C94026
	for <cuongnt@aisc.com.vn>; Fri, 21 Feb 2020 00:30:33 +0700 (+07)
From: Nana Nkrumah <Nana.Nkrumah@kinross.com>
To: cuongnt@aisc.com.vn
Subject: RE: INVOICE DOCUMENTS HSBC BANK
Date: 20 Feb 2020 09:30:27 -0800
Message-ID: <20200220093027.269654B1B47E25CA@kinross.com>
MIME-Version: 1.0
Content-Type: multipart/mixed;
	boundary="----=_NextPart_000_0012_A8F2150E.F2C8A7E4"

This is a multi-part message in MIME format.

------=_NextPart_000_0012_A8F2150E.F2C8A7E4
Content-Type: multipart/alternative;
	boundary="----=_NextPart_001_0013_A8F2150E.F2C8A7E4"

------=_NextPart_001_0013_A8F2150E.F2C8A7E4
Content-Type: text/plain;
	charset="utf-8"
Content-Transfer-Encoding: quoted-printable

Dear cuongnt
------=_NextPart_001_0013_A8F2150E.F2C8A7E4
Content-Type: text/html;
	charset="iso-8859-1"
Content-Transfer-Encoding: quoted-printable

<!DOCTYPE HTML>

<html><head>
<meta name=3D"GENERATOR" content=3D"MSHTML 11.00.10570.1001">
<meta http-equiv=3D"X-UA-Compatible" content=3D"IE=3Dedge">
</head>
<body><div class=3D"gmail_quote"><br>Dear cuongnt</div><div class=3D"gmail_=
quote"><br></div><div class=3D"gmail_quote">FYI<br><br><br>Please Kindly fi=
nd attached confirm Bank Details <br><br><br><font color=3D"#000080" face=
=3D"Arial">Best Regards<br></font><br><br></div></body></html>
------=_NextPart_001_0013_A8F2150E.F2C8A7E4--

------=_NextPart_000_0012_A8F2150E.F2C8A7E4
Content-Type: application/octet-stream; name="Confirm Invoice 41202219-2020.iso"
Content-Transfer-Encoding: base64
Content-Disposition: attachment; filename="Confirm Invoice 41202219-2020.iso"

AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA

**Comment by barrydegraaff** [comment]
The Zimlet works on things found by spam-assassin. 

Right now it checks for the labels URI_PHISH, FREEMAIL_FORGED_REPLYTO and FROMNAME_SPOOF 

Since those are not tagged to your email, it does not work. 


So you probably want to improve your overall ant-spam system, take a look at: 
https://www.missioncriticalemail.com/2019/03/21/zimbra-anti-spam-best-practices-2019/

**Comment by zimico** [comment]
Dear Barry,
Thank for your reply. Yes, We followed this Mr. Mark's blog and have quite good result. However, this zimlet seldom catches the spam email. Maybe because there is no matching rules as you mentioned above.
Best regards,
Minh.

**Comment by barrydegraaff** [comment]
Again, it does only see, what spamassassin sees, so it should be seen as a tool to help end users to alert in case something is 100% spoofing.

You can modify the zimlet, by checking the commits from btactic from last november.
